name: Build
on: [ push, pull_request ]

jobs:
  build:
    uses: okocraft/workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '25'
      package-name: BoxTradeStick-Build-${{ github.run_number }}
      upload-test-results: true
